### PR TITLE
Capstone React-project

### PR DESCRIPTION
**Pull request by OsvaldoBC**
The milestone in this pull request is:

It is a mobile web app for checking a list of metrics (numeric values) that were created using React and Redux. An API was selected that provides numerical data on an existing cryptocurrency in the market. The web app has several pages: a home page with a list of cryptocurrencies that can be filtered by name; a page for the details of each cryptocurrency.

[ Video explaining the project](https://www.loom.com/share/0079dbdc9e68464e8fe39feb4b59463e)

### CODE REVIEW

**Review by AnselemOdims — CHANGES_REQUESTED** [review]
### Hi @OsvaldoBC , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [x] Good job on the video presentation but please kindly tell us about a piece of code that you are proud of in your codebase
- [x] Good job working on the snapshot test, but please kindly include integration tests using React Testing Library

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by OsvaldoBC** [comment]
[Video explaining the project](https://www.loom.com/share/5cd5d9465e294aa388b86030d33c2eb8)

**Review by addod19 — CHANGES_REQUESTED** [review]
### Hi @OsvaldoBC, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Nice job with this amazing project :100: 
  - [ ] The student recorded a video presenting the features of the project
  - [ ] The maximum length of the video is 5 minutes
  - [ ] The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear
  - [ ] The video contains a demo of the project, highlighting all the project features

 ## Required Changes ♻️
_Check the comments under the review._
- [x] Having watched and listen to both videos, here is the list of requirement missing as pointed out in the previous review. Here is a screenshot of the requirement as seen below
Screenshot from 2023-02-10 22-20-47

 

## Optional suggestions
- [ ] It would be better going forward if we kindly capitalize all our commit messages, for example; `Add` instead of `add`, this will help make our PR looks professional :man_technologist: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OsvaldoBC** [comment]
[video explaining the project](https://www.loom.com/share/427f8b7445b64c858ddd81a3b66161db)

**Review by ridwanediallo — APPROVED** [review]
# STATUS: APPROVED 🟢
## Hi @OsvaldoBC , 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
